### ISSUE TITLE
Error occurred while building a filesystem and kernel images for the HSDK with Buildroot

### ISSUE THREAD

**Issue by BarryWang2017** [foss-for-synopsys-dwc-arc-processors/buildroot#6] opened 2019-03-07 04:23 UTC
Hello,
An error occurred when I built the Linux kernel and file system for the HSDK using Buildroot. The screenshot of the error is as follows:
![Error screenshot](https://github.com/BarryWang2017/issus_data/blob/master/2019.03.07/buildroot_error.png?raw=true)

What should I do to rule out this error?

Thank you,
BarryWang

PS:
Build steps:
```shell
git clone https://git.busybox.net/buildroot
cd buildroot
mkdir ../out_git
make O=`readlink -e ../out_git` snps_archs38_hsdk_defconfig
cd ../out_git/
make menuconfig
```
Modify the toolchain  and save.
![Toolchain](https://github.com/BarryWang2017/issus_data/blob/master/2019.03.07/toolchain.png?raw=true)
Building everything
```shell
make V=1
```
The build process lasted for a few minutes and there was such an error:
![Error screenshot](https://github.com/BarryWang2017/issus_data/blob/master/2019.03.07/buildroot_error.png?raw=true)

**Comment by abrodkin** [comment] 2019-03-07 07:49
@BarryWang2017 my first guess will be non US locale.
Could you please show me an output of command `readelf -h vmlinux`?
Note I mean `vmlinux` located in your build folder: `/home/barrywang/ARC-dev/buildroot/out_git/build/linux-4.16.8`.

**Comment by BarryWang2017** [comment] 2019-03-07 09:02
@abrodkin Your guess is correct. 
I changed the host's system language to English and reboot. Then I rebuilt the project, the problem was solved. 
Thank you,
BarryWang

**Comment by abrodkin** [comment] 2019-03-07 11:44
@BarryWang2017 may I close this issue then?

**Comment by BarryWang2017** [comment] 2019-03-07 12:03
Yes, of course, thank you so much!

**Comment by anthony-kolesov** [comment] 2019-03-07 12:21
@BarryWang2017 I'm not sure if this will help with this specific problem, but I think you might also try doing `export LC_ALL=C` before running `make` - thus no need to change language for the whole host and reboot. This used to help me with various issues caused by locales.

**Comment by BarryWang2017** [comment] 2019-03-07 13:38
@anthony-kolesov This method does not work.
Just like the following screenshot, the system language is Chinese, and I run the command `export LC_ALL=C` before `make`. That error appears again.
![error](https://github.com/BarryWang2017/issus_data/blob/master/2019.03.07/lc_all_c_error.png?raw=true)

After modifying the system language, you do not need to restart the host, just re-login the account.

**Closed as completed** 2024-08-26 16:25 UTC
Labels: question
